[package]
name = "moped"
version = "0.1.0"
authors = ["Johan Kristell <johan@jott.se>"]
edition = "2018"
description = "Moped backend server"
license = "MIT"

[dependencies]
async-mpd = "0.2.1"
femme = "2.1.0"
log = "0.4.8"
tide = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.6.0", features = ["attributes"] }
moped-shared = { path = "../shared", version = "0.1" }
