[package]
name = "shared"
version = "0.1.0"
authors = ["Johan Kristell <johan@jott.se>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-mpd = { path = "../../async-mpd", default-features = false }
